### ISSUE TITLE
Add key for abbreviations and acronyms on wiring diagram overview

### ISSUE THREAD

**Issue by dougierad** [duckietown/docs-opmanual_sky#124]
In the Part A Build page, there is a nice, graphical wiring diagram of a complete build. However, there are many abbreviations and acronyms on the diagram: PWM, PDB, IR, ADC, and others. It would be useful to have a key that spells out the full names of those items.

**Comment by GarrettWarren** [comment]
Great idea, the diagram has a legend now!
