### ISSUE TITLE
How do you submit an issue

### ISSUE THREAD

**Issue by jonesv475** [duckietown/docs-opmanual_sky#133]
Could leave instructions on how to submit an issue

**Comment by ecopeley** [comment]
You make a great point!

**Comment by GarrettWarren** [comment]
A great point indeed! Currently we have instructions in the student book, but feel free to reopen this issue if you think it would be a good idea to put instructions in the build docs as well 

student book instructions can be found near the bottom of this page https://docs.duckietown.org/daffy/duckiesky_high_school_student/out/introduction_curriculum_github.html
